import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FormControl, InputLabel, MenuItem, Select, } from "@mui/material";
import { useCallback } from "react";
import { LotEnum, lotNameToLabel } from "../../core/enums/LotEnum";
export default function LotSelectInput({ selectedLot, setSelectedLot, }) {
    const handleChange = useCallback(async (event) => {
        const newSelectedLot = event.target.value === "" ? null : event.target.value;
        setSelectedLot(newSelectedLot);
    }, [setSelectedLot]);
    return (_jsxs(FormControl, { fullWidth: true, children: [_jsx(InputLabel, { id: "lot-select-input", children: "Lot" }), _jsxs(Select, { labelId: "demo-simple-select-label", id: "lot-select-input", value: selectedLot || "", label: "Lot", onChange: handleChange, fullWidth: true, children: [_jsx(MenuItem, { value: "", children: _jsx("em", { children: "Aucune " }) }), _jsx(MenuItem, { value: LotEnum.VRD_1, children: lotNameToLabel(LotEnum.VRD_1) }), _jsx(MenuItem, { value: LotEnum.FONDATION_2, children: lotNameToLabel(LotEnum.FONDATION_2) }), _jsx(MenuItem, { value: LotEnum.SUPERSTRUCTURE_3, children: lotNameToLabel(LotEnum.SUPERSTRUCTURE_3) }), _jsx(MenuItem, { value: LotEnum.CHARPENTE_4, children: lotNameToLabel(LotEnum.CHARPENTE_4) }), _jsx(MenuItem, { value: LotEnum.CLOISONNEMENT_5, children: lotNameToLabel(LotEnum.CLOISONNEMENT_5) }), _jsx(MenuItem, { value: LotEnum.FACADE_6, children: lotNameToLabel(LotEnum.FACADE_6) }), _jsx(MenuItem, { value: LotEnum.REVETEMENT_7, children: lotNameToLabel(LotEnum.REVETEMENT_7) }), _jsx(MenuItem, { value: LotEnum.CVC_8, children: lotNameToLabel(LotEnum.CVC_8) }), _jsx(MenuItem, { value: LotEnum.SANITAIRES_9, children: lotNameToLabel(LotEnum.SANITAIRES_9) }), _jsx(MenuItem, { value: LotEnum.CFO_10, children: lotNameToLabel(LotEnum.CFO_10) }), _jsx(MenuItem, { value: LotEnum.CFA_11, children: lotNameToLabel(LotEnum.CFA_11) }), _jsx(MenuItem, { value: LotEnum.ELEVATEUR_12, children: lotNameToLabel(LotEnum.ELEVATEUR_12) }), _jsx(MenuItem, { value: LotEnum.PRODUCTION_ELECTRICITE_13, children: lotNameToLabel(LotEnum.PRODUCTION_ELECTRICITE_13) }), _jsx(MenuItem, { value: LotEnum.ENERGIE, children: lotNameToLabel(LotEnum.ENERGIE) }), _jsx(MenuItem, { value: LotEnum.AUTRE, children: lotNameToLabel(LotEnum.AUTRE) })] })] }));
}
